<a href="https://colab.research.google.com/github/simoneminorr/ds1002-uqa9qp/blob/main/practice_with_messy_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
messy= dupes = pd.read_csv('very-messy-data.csv')

In [3]:
messy.tail(40)
#1315 rows of data

       id  sepal_length  sepal_width  petal_length  petal_width    species
1276  377           5.6          NaN           1.9          1.4        NaN
1277  378           4.3          3.0           1.1          3.0     setosa
1278  379           4.8          3.7           2.1          2.4  virginica
1279  380           5.8          3.2           2.4          2.6     setosa
1280  381           5.5          3.4           2.5          0.5     setosa
1281  382           4.1          3.9           1.7          2.0  virginica
1282  383           4.6          3.3           2.9          2.9     setosa
1283  384           3.7          2.6           1.1          1.0  virginica
1284  385           3.4          3.9           2.0          0.1     setosa
1285  386           3.4          3.6           1.0          0.7  virginica
1286  387           4.7          2.4           2.3          1.7     setosa
1287  388           4.9          2.1           1.5          1.7     setosa
1288  389           3.6          3.3           1.8          NaN  virginica
1289  390           5.3          2.2           2.0          2.1  virginica
1290  391           4.5          3.3           NaN          2.3  virginica
1291  392           4.1          NaN           1.8          0.2     setosa
1292  393           4.0          3.0           1.8          2.5  virginica
1293  394           4.8          NaN           1.5          2.0  virginica
1294  395           3.4          2.8           3.0          1.0     setosa
1295  396           NaN          2.9           1.5          NaN  virginica
1296  397           3.9          2.3           2.5          1.4     setosa
1297  398           4.0          3.8           2.9          0.3     setosa
1298  399           4.1          2.8           1.6          NaN     setosa
1299  400           5.1          NaN           2.1          0.9  virginica
1300  401           5.7          2.7           2.8          2.3  virginica
1301  402           5.4          3.7           NaN          2.6     setosa
1302  403           4.7          2.0           1.8          1.6     setosa
1303  404           4.8          3.2           2.9          0.6  virginica
1304  405           4.9          4.0           NaN          0.4        NaN
1305  406           3.2          NaN           1.7          0.8     setosa
1306  407           3.3          2.1           1.8          1.9  virginica
1307  408           3.2          3.4           NaN          0.7  virginica
1308  409           3.3          3.4           2.5          2.5  virginica
1309  410           4.5          3.4           1.9          1.7     setosa
1310  411           4.8          2.6           1.9          0.9     setosa
1311  412           NaN          3.6           2.9          0.5  virginica
1312  413           5.8          2.7           2.0          0.1  virginica
1313  414           3.3          3.7           1.3          2.8     setosa
1314  415           3.1          NaN           1.1          NaN  virginica
1315  416           4.3          2.5           1.3          1.0     setosa

In [4]:
len(messy)
#total rows is 1316 with 1 being a header

1316

In [5]:
messy.head

<bound method NDFrame.head of        id  sepal_length  sepal_width  petal_length  petal_width    species
0       1           3.5          2.9           1.4          0.5  virginica
1       2           3.6          3.2           3.0          0.5     setosa
2       3           3.8          NaN           2.2          1.5     setosa
3       4           5.8          2.7           2.6          1.2  virginica
4       5           4.9          3.6           3.0          1.2  virginica
...   ...           ...          ...           ...          ...        ...
1311  412           NaN          3.6           2.9          0.5  virginica
1312  413           5.8          2.7           2.0          0.1  virginica
1313  414           3.3          3.7           1.3          2.8     setosa
1314  415           3.1          NaN           1.1          NaN  virginica
1315  416           4.3          2.5           1.3          1.0     setosa

[1316 rows x 6 columns]>

In [7]:
messy.columns

Index(['id', 'sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [8]:
messy.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1311     True
1312     True
1313     True
1314     True
1315     True
Length: 1316, dtype: bool

In [9]:
print(messy.duplicated().sum())

316

In [11]:
nomesszone = messy.drop_duplicates()
nomesszone

       id  sepal_length  sepal_width  petal_length  petal_width    species
0       1           3.5          2.9           1.4          0.5  virginica
1       2           3.6          3.2           3.0          0.5     setosa
2       3           3.8          NaN           2.2          1.5     setosa
3       4           5.8          2.7           2.6          1.2  virginica
4       5           4.9          3.6           3.0          1.2  virginica
..    ...           ...          ...           ...          ...        ...
995   996           4.5          3.6           NaN          2.7     setosa
996   997           4.0          2.1           NaN          2.1     setosa
997   998           5.9          2.5           2.1          2.5  virginica
998   999           5.0          2.6           1.9          NaN        NaN
999  1000           3.4          3.9           1.9          1.5     setosa

[1000 rows x 6 columns]

In [12]:
len(nomesszone)

1000

In [13]:
import numpy as np

In [16]:
dfmess= pd.DataFrame('very-messy-data.csv')

ValueError: ignored

In [15]:
minimalmess= df_miss.fillna(df_miss.median())

NameError: ignored