<a href="https://colab.research.google.com/github/simoneminorr/ds1002-uqa9qp/blob/main/homework/week-7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Week 7

Complete the following blocks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

Load the following dataset into pandas and perform the requested operations in code.

Source: https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv

In [3]:
# Load pandas and the data
import pandas as pd
rideshares= pd.read_csv('https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv')

In [4]:
# show how many rows and columns are in this dataset
rideshares.shape

(25760, 10)

In [5]:
# The first column, "duration" is seen as a string.
# Using two snippets of code, clean this column up so that
# is now an integer (int64)
rideshares['duration'] = rideshares['duration'].str.strip('minutes')
rideshares['duration'] = rideshares['duration'].astype('int')

In [6]:
# Now display the datatypes in the updated dataframe
rideshares.dtypes

duration            int64
station_A_id        int64
station_A_name     object
station_B_id        int64
station_B_name     object
bike_id             int64
user_type           int64
user_birth_year     int64
user_gender        object
tire_size           int64
dtype: object

In [7]:
# Show the min and max values of ride durations (the shortest and longest rides)
# Hint: If 'df' is the name of your dataframe, simply specify the column name
# and then append the .min() or .max() methods.
rideshares['duration'].min()

1

In [8]:
rideshares['duration'].max()

1372

In [9]:
# Create a new dataframe object and populate it with rides that are 60 minutes or less.
# Hint: Use the .query() method for the dataframe that we used in class.
rideshares_shorter= rideshares.query('duration <= 60')

In [10]:
# Now show both the min and max values of the duration column for your new dataset.
rideshares_shorter['duration'].min()

1

In [11]:
rideshares_shorter['duration'].max()

60

In [12]:
# Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.
rideshares_shorter.query('tire_size==26')

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
6,16,67,San Francisco Caltrain Station 2 (Townsend St...,107,17th St at Dolores St,1035,2,1981,Male,26
9,5,30,San Francisco Caltrain (Townsend St at 4th St),62,Victoria Manalo Draves Park,333,1,1994,Male,26
12,7,3,Powell St BART Station (Market St at 4th St),27,Beale St at Harrison St,1863,3,1998,Male,26
...,...,...,...,...,...,...,...,...,...,...
25750,15,16,Steuart St at Market St,371,Lombard St at Columbus Ave,4372,2,1994,Male,26
25751,15,16,Steuart St at Market St,371,Lombard St at Columbus Ave,5246,1,1995,Male,26
25755,11,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26

In [14]:
rideshares_shorter.up26date= rideshares_shorter.query('tire_size==26')

In [13]:
# ALTERNATIVE
#Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.
rideshares_shorter.up26date = rideshares_shorter['tire_size']== '26'

<ipython-input-13-0d8f5b5e41bd>:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  rideshares_shorter.up26date = rideshares_shorter['tire_size']== '26'

In [21]:
# Finally, produce a count of all records with FEMALE riders
# using the 26-inch wheeled rental bikes for their rentals of
# one hour or less.
rideshares_shorter.up26date.groupby('user_gender').mean()

<ipython-input-21-794600b01233>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  rideshares_shorter.up26date.groupby('user_gender').mean()

,duration,station_A_id,station_B_id,bike_id,user_type,user_birth_year,tire_size
user_gender,,,,,,,
Female,11.344362,32.228562,92.068197,4075.242404,2.013842,1985.296759,26.0
Male,9.794390,30.879273,87.031169,4118.282805,2.006026,1982.432623,26.0
Other,10.724138,30.264368,87.166667,4146.902299,1.994253,1983.011494,26.0